version: '3.8'

services:
  postgres:
    build: 
      context: ../../images/postgres
      dockerfile: ../../images/postgres/Dockerfile
    image: postgres
    command: postgres -c 'shared_buffers=1GB'
    shm_size: '1GB'
    stdin_open: true
    tty: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: project
    volumes:
      - ../../../workspace:/workspace
      - ../../mounts/postgres/data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    extra_hosts:
      - "localhost:127.0.0.1"
      
  python_env:
    build: 
      context: ../../images/python_env
      dockerfile: ../../images/python_env/Dockerfile
    image: python_env
    stdin_open: true
    tty: true
    volumes:
      - ../../../workspace:/workspace
    expose:
      - "8080"
      - "443"
    ports:
      - "8080:8080"
      - "443:443"
